baseurl = "https://www.mrbits.com.br/"
title = "MrBiTs' Own Website"
copyright = "Copyright (c) 2017, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "base16"
PygmentsCodeFences = "True"
googleAnalytics = "UA-4159326-1"

[author]
  name = "MrBiTs"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech, hacking, mrbits"
  description = "MrBiTs' Own Website"

[params]
  github = "mrbitsdcf"
  gitlab = "mrbitsdcf"
  email = "mrbits@mrbits.com.br"
